Fix types to reflect OS Core (#50)
* Fix types of OSCoreClient

This silences type errors in OS Core:

```
identity/clients/__init__.py:13: error: Argument 1 to "PermissionsClient" has incompatible type "OSCoreClientImpl"; expected "OSCoreClient"
identity/clients/__init__.py:13: note: Following member(s) of "OSCoreClientImpl" have conflicts:
identity/clients/__init__.py:13: note:     Expected:
identity/clients/__init__.py:13: note:         def fetch_persons_with_permission(self, scope: str, org_ref: Union[str, UUID]) -> List[str]
identity/clients/__init__.py:13: note:     Got:
identity/clients/__init__.py:13: note:         def fetch_persons_with_permission(self, scope: str, org_ref: Union[str, UUID]) -> List[Dict[Any, Any]]
identity/clients/__init__.py:13: note:     Expected:
identity/clients/__init__.py:13: note:         def fetch_persons_with_permission_for_location(self, scope: str, location_type: Union[Literal['company'], Literal['vendor']], location_id: int) -> List[str]
identity/clients/__init__.py:13: note:     Got:
identity/clients/__init__.py:13: note:         def fetch_persons_with_permission_for_location(self, scope: 
```

The functions changed are only used in OS Core, and they are typed as
such there.

See: https://github.com/managedbyq/os-core/blob/446fdfdf6728b46942ed68f3154877f13a537d8a/identity/clients/permissions_protocol_impl.py#L116-L133
See: https://github.com/managedbyq/os-core/blob/446fdfdf6728b46942ed68f3154877f13a537d8a/identity/controllers/permissions.py#L195-L214
See: https://github.com/managedbyq/os-core/blob/446fdfdf6728b46942ed68f3154877f13a537d8a/identity/views.py#L380-L420

* Bump to 1.3.3